### ISSUE TITLE
For factorial of 1

### ISSUE THREAD

**Issue by TusharSMachale** [Siddheshwar161970/sbm_codes#10]

**Comment by Siddheshwar161970** [comment]
@TusharSMachale  solve and send

**Comment by TusharSMachale** [comment]
#include <stdio.h>
int main() {
    int n, i;
    unsigned long long fact = 1;
    printf("Enter an integer: ");
    scanf("%d", &n);

    // shows error if the user enters a negative integer
    if (n < 0)
        printf("Error! Factorial of a negative number doesn't exist.");
    else {
        for (i = 1; i <= n; ++i) {
            fact *= i;
        }
        printf("Factorial of %d = %llu", n, fact);
    }

    return 0;
}

**Comment by Siddheshwar161970** [comment]
@TusharSMachale correct
